<?php

use Illuminate\Database\Seeder;

class ApartmentsTableAutoSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('apartments')->delete();
        
        \DB::table('apartments')->insert(array (
            0 => 
            array (
                'id' => '2',
                'title' => 'Edificio Galvan - Monoambiente',
                'slug' => 'edificio-galvan-monoambiente',
                'floor' => '1',
                'department' => 'B',
                'price' => '92250',
                'rooms' => '1',
                'dormitorios' => '1',
                'banios' => '1',
                'toilettes' => '1',
                'antiguedad' => '0',
                'expensas' => '0',
                'orientacion' => 'Norte',
                'disposicion' => 'Frente',
                'area' => '36',
                'area_semicubierta' => NULL,
                'area_total_construido' => NULL,
                'description' => 'Galvan 3051 es un edificio de departamentos residenciales aptos profesionales que ofrecen el máximo confort articulando espacios flexibles para vivir, trabajar y estudiar o como proyecto de inversión. El emprendimiento se desarrolla en un terreno de 1815 m2, consta de planta baja libre, siete niveles y un primer retiro con viviendas más otro con espacios comunes y amenities. Al frente se ubican siete unidades de 3 ambientes y una de 2 ambientes en suite con vestidor y toilette de recepción y al contra frente dieciséis unidades monoambientes. En el segundo retiro se proyectan la portería, un sauna con toilette y ducha y una expansión aterrazada con parilla común. En la terraza del último nivel se ubica un solárium y una pequeña piscina con jacuzzi. El espacio de guardacoches destinado en la planta baja tiene una capacidad para 8 vehículos.',
                'status' => 'A_estrenar',
                'contact_name' => 'Maria',
                'contact_phone' => '1153294260',
                'building_id' => '23',
                'created_at' => '2019-07-18 10:55:42',
                'updated_at' => '2019-08-15 23:50:34',
                'code' => '2',
            ),
            1 => 
            array (
                'id' => '8',
                'title' => 'Edificio Galvan -  3 Ambientes',
                'slug' => 'edificio-galvan-3-ambientes',
                'floor' => '2',
                'department' => 'c',
                'price' => '222860',
                'rooms' => '3',
                'dormitorios' => '2',
                'banios' => '1',
                'toilettes' => '1',
                'antiguedad' => '0',
                'expensas' => '0',
                'orientacion' => NULL,
                'disposicion' => 'Contrafrente',
                'area' => '76',
                'area_semicubierta' => NULL,
                'area_total_construido' => NULL,
                'description' => 'Galvan 3051 es un edificio de departamentos residenciales aptos profesionales que ofrecen el máximo confort articulando espacios flexibles para vivir, trabajar y estudiar o como proyecto de inversión. El emprendimiento se desarrolla en un terreno de 1815 m2, consta de planta baja libre, siete niveles y un primer retiro con viviendas más otro con espacios comunes y amenities. Al frente se ubican siete unidades de 3 ambientes y una de 2 ambientes en suite con vestidor y toilette de recepción y al contra frente dieciséis unidades monoambientes. En el segundo retiro se proyectan la portería, un sauna con toilette y ducha y una expansión aterrazada con parilla común. En la terraza del último nivel se ubica un solárium y una pequeña piscina con jacuzzi. El espacio de guardacoches destinado en la planta baja tiene una capacidad para 8 vehículos.',
                'status' => 'En_obra',
                'contact_name' => 'Maria',
                'contact_phone' => '1153294260',
                'building_id' => '23',
                'created_at' => '2019-08-15 23:42:38',
                'updated_at' => '2019-08-16 15:32:07',
                'code' => 'A',
            ),
            2 => 
            array (
                'id' => '9',
                'title' => 'Edificio Galvan -1 Monoambiente',
                'slug' => 'edificio-galvan-1-monoambiente',
                'floor' => '2',
                'department' => 'B',
                'price' => '95940',
                'rooms' => '1',
                'dormitorios' => '1',
                'banios' => '1',
                'toilettes' => '0',
                'antiguedad' => '0',
                'expensas' => '0',
                'orientacion' => 'Norte',
                'disposicion' => 'Frente',
                'area' => '37',
                'area_semicubierta' => NULL,
                'area_total_construido' => NULL,
                'description' => 'Galvan 3051 es un edificio de departamentos residenciales aptos profesionales que ofrecen el máximo confort articulando espacios flexibles para vivir, trabajar y estudiar o como proyecto de inversión. El emprendimiento se desarrolla en un terreno de 1815 m2, consta de planta baja libre, siete niveles y un primer retiro con viviendas más otro con espacios comunes y amenities. Al frente se ubican siete unidades de 3 ambientes y una de 2 ambientes en suite con vestidor y toilette de recepción y al contra frente dieciséis unidades monoambientes. En el segundo retiro se proyectan la portería, un sauna con toilette y ducha y una expansión aterrazada con parilla común. En la terraza del último nivel se ubica un solárium y una pequeña piscina con jacuzzi. El espacio de guardacoches destinado en la planta baja tiene una capacidad para 8 vehículos.',
                'status' => 'A_estrenar',
                'contact_name' => 'Maria',
                'contact_phone' => '1153294260',
                'building_id' => '23',
                'created_at' => '2019-08-15 23:50:55',
                'updated_at' => '2019-08-16 14:57:12',
                'code' => 'B',
            ),
            3 => 
            array (
                'id' => '10',
                'title' => 'Edificio Galvan - Monoambiente Modular',
                'slug' => 'edificio-galvan-monoambiente-modular',
                'floor' => '1',
                'department' => 'c',
                'price' => '111250',
                'rooms' => '1',
                'dormitorios' => '1',
                'banios' => '1',
                'toilettes' => '0',
                'antiguedad' => '0',
                'expensas' => '0',
                'orientacion' => NULL,
                'disposicion' => 'Contrafrente',
                'area' => '45',
                'area_semicubierta' => NULL,
                'area_total_construido' => NULL,
                'description' => 'Galvan 3051 es un edificio de departamentos residenciales aptos profesionales que ofrecen el máximo confort articulando espacios flexibles para vivir, trabajar y estudiar o como proyecto de inversión. El emprendimiento se desarrolla en un terreno de 1815 m2, consta de planta baja libre, siete niveles y un primer retiro con viviendas más otro con espacios comunes y amenities. Al frente se ubican siete unidades de 3 ambientes y una de 2 ambientes en suite con vestidor y toilette de recepción y al contra frente dieciséis unidades monoambientes. En el segundo retiro se proyectan la portería, un sauna con toilette y ducha y una expansión aterrazada con parilla común. En la terraza del último nivel se ubica un solárium y una pequeña piscina con jacuzzi. El espacio de guardacoches destinado en la planta baja tiene una capacidad para 8 vehículos.',
                'status' => 'En_obra',
                'contact_name' => 'Maria',
                'contact_phone' => '1153294260',
                'building_id' => '23',
                'created_at' => '2019-08-16 10:05:14',
                'updated_at' => '2019-08-16 15:35:00',
                'code' => 'C',
            ),
            4 => 
            array (
                'id' => '11',
                'title' => 'Edificio Galvan -Monoambiente Modular',
                'slug' => 'edificio-galvan-monoambiente-modular',
                'floor' => '2',
                'department' => 'c',
                'price' => '115700',
                'rooms' => '1',
                'dormitorios' => '1',
                'banios' => '1',
                'toilettes' => '0',
                'antiguedad' => '0',
                'expensas' => '0',
                'orientacion' => NULL,
                'disposicion' => 'Contrafrente',
                'area' => '45',
                'area_semicubierta' => NULL,
                'area_total_construido' => NULL,
                'description' => 'Galvan 3051 es un edificio de departamentos residenciales aptos profesionales que ofrecen el máximo confort articulando espacios flexibles para vivir, trabajar y estudiar o como proyecto de inversión. El emprendimiento se desarrolla en un terreno de 1815 m2, consta de planta baja libre, siete niveles y un primer retiro con viviendas más otro con espacios comunes y amenities. Al frente se ubican siete unidades de 3 ambientes y una de 2 ambientes en suite con vestidor y toilette de recepción y al contra frente dieciséis unidades monoambientes. En el segundo retiro se proyectan la portería, un sauna con toilette y ducha y una expansión aterrazada con parilla común. En la terraza del último nivel se ubica un solárium y una pequeña piscina con jacuzzi. El espacio de guardacoches destinado en la planta baja tiene una capacidad para 8 vehículos.',
                'status' => 'En_obra',
                'contact_name' => 'Maria',
                'contact_phone' => '1153294260',
                'building_id' => '23',
                'created_at' => '2019-08-16 10:06:32',
                'updated_at' => '2019-08-16 10:06:32',
                'code' => 'A',
            ),
            5 => 
            array (
                'id' => '14',
                'title' => 'Edificio Galvan - Monoambiente Modular',
                'slug' => 'edificio-galvan-monoambiente-modular',
                'floor' => '2',
                'department' => 'B',
                'price' => '95940',
                'rooms' => '1',
                'dormitorios' => '1',
                'banios' => '1',
                'toilettes' => '0',
                'antiguedad' => '0',
                'expensas' => '0',
                'orientacion' => NULL,
                'disposicion' => 'Contrafrente',
                'area' => '37',
                'area_semicubierta' => NULL,
                'area_total_construido' => NULL,
                'description' => 'Galvan 3051 es un edificio de departamentos residenciales aptos profesionales que ofrecen el máximo confort articulando espacios flexibles para vivir, trabajar y estudiar o como proyecto de inversión. El emprendimiento se desarrolla en un terreno de 1815 m2, consta de planta baja libre, siete niveles y un primer retiro con viviendas más otro con espacios comunes y amenities. Al frente se ubican siete unidades de 3 ambientes y una de 2 ambientes en suite con vestidor y toilette de recepción y al contra frente dieciséis unidades monoambientes. En el segundo retiro se proyectan la portería, un sauna con toilette y ducha y una expansión aterrazada con parilla común. En la terraza del último nivel se ubica un solárium y una pequeña piscina con jacuzzi. El espacio de guardacoches destinado en la planta baja tiene una capacidad para 8 vehículos.',
                'status' => 'En_obra',
                'contact_name' => 'Maria',
                'contact_phone' => '1153294260',
                'building_id' => '23',
                'created_at' => '2019-08-16 14:32:57',
                'updated_at' => '2019-08-16 14:38:19',
                'code' => 'A',
            ),
            6 => 
            array (
                'id' => '16',
                'title' => 'Edificio Galvan -  3 Ambientes',
                'slug' => 'edificio-galvan-3-ambientes',
                'floor' => '2',
                'department' => 'c',
                'price' => '222860',
                'rooms' => '3',
                'dormitorios' => '2',
                'banios' => '1',
                'toilettes' => '1',
                'antiguedad' => '0',
                'expensas' => '0',
                'orientacion' => NULL,
                'disposicion' => 'Contrafrente',
                'area' => '76',
                'area_semicubierta' => NULL,
                'area_total_construido' => NULL,
                'description' => 'Galvan 3051 es un edificio de departamentos residenciales aptos profesionales que ofrecen el máximo confort articulando espacios flexibles para vivir, trabajar y estudiar o como proyecto de inversión. El emprendimiento se desarrolla en un terreno de 1815 m2, consta de planta baja libre, siete niveles y un primer retiro con viviendas más otro con espacios comunes y amenities. Al frente se ubican siete unidades de 3 ambientes y una de 2 ambientes en suite con vestidor y toilette de recepción y al contra frente dieciséis unidades monoambientes. En el segundo retiro se proyectan la portería, un sauna con toilette y ducha y una expansión aterrazada con parilla común. En la terraza del último nivel se ubica un solárium y una pequeña piscina con jacuzzi. El espacio de guardacoches destinado en la planta baja tiene una capacidad para 8 vehículos.',
                'status' => 'En_obra',
                'contact_name' => 'Maria',
                'contact_phone' => '1153294260',
                'building_id' => '23',
                'created_at' => '2019-08-16 14:34:30',
                'updated_at' => '2019-08-16 14:54:44',
                'code' => 'A',
            ),
        ));
        
        
    }
}